export enum APP_MODULES {
  USERS = 'USERS',
  HEADQUARTERS = 'HEADQUARTERS',
  USER_AREA = 'USER_AREA',
  USER_POSITION = 'USER_POSITION',
  USER_ROLES = 'USER_ROLES',
  TENANT = 'TENANT',
  FILES = 'FILES',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SETTING = 'SETTING',
  MEMBERSHIP = 'MEMBERSHIP',
  MEDICAL_SPECIALTIES= 'MEDICAL_SPECIALTIES',
  DATA_PARAMETERIZATION = 'DATA_PARAMETERIZATION',
  PATIENT= 'PATIENT',
  MEDICAL_RECORDS = 'MEDICAL_RECORDS',
  QUICK_MEDICAL_HISTORY = 'QUICK_MEDICAL_HISTORY',
  PHARMACOLOGICAL_MANAGEMENT = 'PHARMACOLOGICAL_MANAGEMENT',
  QUICK_COMPREHENSIVE_MANAGEMENT = 'QUICK_COMPREHENSIVE_MANAGEMENT',
  QUICK_PARACLINICS_EVALUATIONS= 'QUICK_PARACLINICS_EVALUATIONS',
  QUICK_PHYSICAL_EXAM= 'QUICK_PHYSICAL_EXAM',

}



